[versions]
vineflower = "1.11.2"
teavm = "0.13.0"

[libraries]
vineflower = { group = "org.vineflower", name = "vineflower", version.ref = "vineflower" }
teavm-core = { group = "org.teavm", name = "teavm-core", version.ref = "teavm" }

[plugins]
teavm = { id = "org.teavm", version.ref = "teavm" }
blossom = { id = "net.kyori.blossom", version = "2.1.0" }
